### ISSUE TITLE
About the Crab Online Hackathon

### ISSUE THREAD

**Issue by 1022ranji** [125johnwick/MyWeb3Club#2]
Hi, we noticed that you've participated in Crab Online Hackathon. But the website and the backend are not open-source, only the contract is open source, which will affect the score. If you don't mind, could you please add it?

**Comment by 125johnwick** [comment]
Hey RanJi,
Sorry, I just saw your email, my front-end open source code is here.

https://github.com/125johnwick/MyWeb3Club-Web

myweb3.club has no backend, the frontend directly calls the contract.

**Comment by 1022ranji** [comment]
Alright, thank you.

**Comment by 1022ranji** [comment]
done
